### ISSUE TITLE
HDR doesn't work properly with ZetaLoader.

### ISSUE THREAD

**Issue by omegamalkior** [Aetopia/ZetaLoader#1]
Title. It doesn't look this dim when launched through the regular Halo Infinite launcher. But with ZetaLoader it looks like as if it's outputting the game in SDR mode even when HDR is toggled.

**Comment by omegamalkior** [comment]
Hello, thank you for the prompt response. Tho I think this was due on my end. I hadn't opened Halo Infinite in a long time and it seems their HDR implementation has changed a bit so I had to alter my monitors brightness and now it looks as it did back then (or close enough). If anyone else reports on it then feel free to keep bug testing, but at least for now issue should be closed on my end. Thanks again.

**Comment by Aetopia** [comment]
Thank you!
